function [Char] = Start
Char = [1 0 1 1 1];
f1 = figure('Visible','off',...
    'Name','Welcome',...
    'Position',[535 275 500 300],'MenuBar','none');

txt = uicontrol('Style','text',...
    'Position',[158 273 185 30],...
    'String','Welcome to your Quest!',...
    'FontName','Poor Richard',...
    'FontSize',15);

Name = uicontrol('Style','edit',...
    'Position',[168 243 100 30]);

Name1= uicontrol('Style','pushbutton', 'String','Enter',...
    'FontName','Poor Richard',...
    'FontSize',12,...
    'Position',[268 243 50 30],...
    'Callback', @Enter);
Easy= uicontrol('Style','checkbox',...
    'Position',[268 200 100 30],...
    'String','Easy Mode?','CallBack',@Easy1);
Start2 = uicontrol('Style','text','Visible','off',...
    'String',"You're Dr. Busick!?",...
    'FontName','Poor Richard',...
    'FontSize',14,...
    'Position',[158 253 200 30]);

Start3 = uicontrol('Style','text','Visible','off',...
    'String','The Bell Laboratory is under attack by monsters! Find and kill the Serpent and Dragon!',...
    'FontName','Poor Richard',...
    'FontSize',14,...
    'Position',[120 183 275 70]);

HP = uicontrol('Style','text','Visible','off',...
    'String','Vitality: 1',...
    'FontName','Poor Richard',...
    'FontSize',14,...
    'Position',[200 150 100 30]);
ST = uicontrol('Style','text','Visible','off',...
    'String','Strength: 1',...
    'FontName','Poor Richard',...
    'FontSize',14,...
    'Position',[200 120 100 30]);
DX = uicontrol('Style','text','Visible','off',...
    'String','Dexterity: 1',...
    'FontName','Poor Richard',...
    'FontSize',14,...
    'Position',[200 90 100 30]);


Start4= uicontrol('Style','pushbutton', 'String','Begin',...
    'Visible','off',...
    'FontName','Poor Richard',...
    'FontSize',12,...
    'Position',[223 50 55 30],...
    'Callback', @Begin);

f1.Visible = 'on';
    function Easy1(~,~)
        Char = [1 0 3 3 3];
        DX.String = 'Dexterity: 3';
        ST.String = 'Strength: 3';
        HP.String = 'Vitality: 3';
    end
    function Enter(~,~)
        pause(1/4)
        Name.Visible = 'off';
        Name1.Visible = 'off';
        Easy.Visible = 'off';
        Start2.Visible = 'on';
        Start3.Visible = 'on';
        txt.Visible = 'off';
        Start4.Visible = 'on';
        HP.Visible = 'on';
        ST.Visible = 'on';
        DX.Visible = 'on';

    end
    function Begin(~,~)
        pause(1/3)
        close(f1)
        
    end
    waitfor(f1)  
end